version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webshop
  front:
    container_name: IPRWC-Front
    image: brianrat2000/iprwc-front
    restart: always
    ports:
      - "4200:4200"
  back:
    container_name: IPRWC-Back
    image: brianrat2000/iprwc-back
    restart: always
    ports:
      - "8080:8080"